name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build an app
        run: |
          make build-app

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Push Docker image to Harbor
        run: |
          docker tag fetch-system/streams:latest ${{ secrets.HARBOR_REGISTRY }}/fetch-system/streams:${GITHUB_SHA::7}
          docker push ${{ secrets.HARBOR_REGISTRY }}/fetch-system/streams:${GITHUB_SHA::7}

  kustomize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Extract image tag
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Update image tag
        uses: Goboolean/manifests/.github/actions/update-image-tag@main
        with:
          app-name: ${{ github.event.repository.name }}
          image-tag: ${{ env.SHORT_SHA }}
          id: ${{ secrets.IMAGE_TAG_UPDATE_APP_ID }}
          private-key: ${{ secrets.IMAGE_TAG_UPDATE_APP_PRIVATE_KEY }}
          profile: dev
          pull-request-link: ${{ github.event.pull_request.html_url }}
